### ISSUE TITLE
Does not handle commands when a path is specified that contains folders where the case does not match

### ISSUE THREAD

**Issue by mdell-seradex** [mdell-seradex/proftpd-mod_case#1]
When an ftp command is sent that specifies folders along with a file name, or an end folder (which I will call a file from this point forward) and the case of the specified folders do not match what is on disk, the command fails.
Examples:
Given that the FTP server has this file in the specified sub-folder: `/v1.2/Modules/AddPercent.zip`  the following commands will fail:
`RETR /V1.2/modules/AddPercent.zip` `CWD /V1.2/modules` `LIST /V1.2/modules/AddPercent.zip` because neither `V1.2` nor `modules` exist.

**Comment by mdell-seradex** [comment]
I removed that reference from the commit, but due to GitHub behaviour, it cannot be removed from the issue.  It is relevant though, I was just trying to get it to link like I have seen in other repros.
That said, TJ has requested that I make other changes before the possibility of this pull request being accepted.

I really think since this really only partially addresses the actual issue, more changes need to be completed before it is accepted.
I am currently waiting on a message from TJ (@Castaglia) before making the current changes he requested.

**Comment by Castaglia** [comment]
Can you provide the `mod_case` configuration you're using, the generated `CaseLog`, and the ProFTPD debug logging, for the failing commands?

**Comment by mdell-seradex** [comment]
I have had trouble setting up the ProFTPD debug logging, but will try again.
Here is the `mod_case` configuration I used:
```
  <IfModule mod_case.c>
    CaseEngine on

    # Enable case-insensitivity only for downloads
    CaseIgnore RETR,SIZE,LIST
    CaseLog /var/log/proftpd/proftpd-case.log
  </IfModule>
```
I am generating the debug logging and Case Log.
Note that this will be using the `mod_case.c` version attached to #2 which does not contain my changes here, but does contain 3 extra lines of logging into the CaseLog file as that will also demonstrate issue #2.

**Comment by mdell-seradex** [comment]
Hi @Castaglia.
Hopefully this contains the logs you need.  I can adjust anything as needed.  Note that I tried to remove identifiable info.
~File removed~

**Comment by mdell-seradex** [comment]
@Castaglia, I was thinking it would be more useful for me to change the extra case logging that I added as per #2 to redirect it to the standard logs, but I am not 100% sure how to do that.
Hopefully this will help give you a clearer picture of what is happening for both this and #2.

**Comment by mdell-seradex** [comment]
Note that it is possible that it may require that the current working directory is not the folder where the file exists which the command is attempting to access.
Typically, in my case, the current working is "/".

**Comment by mdell-seradex** [comment]
@Castaglia if I have missed anything that you need, did not generate the information correctly, or you need more data, please do not hesitate to ask me.
Thank you

**Comment by Castaglia** [comment]
OK, I see what the issue is now.  Am evaluating your change, and other alternative approaches.

One thing which makes this interesting is that I do a lot of module development on a Mac OSX machine.  Macs have case-preserving but case-insensitive filesystems by default -- which means that I would not have encountered this issue during local development/testing, sadly.

**Comment by mdell-seradex** [comment]
Thank you @Castaglia.
Make sure you also note the change I did in mdell-seradex/proftpd-mod_case@8b58e5e805f7d863277745be52f77e39149666f6 as that eliminates a bug that I found in your original repo.
The update you provide for this will address an issue we have in house because we were forced to replace a Microsoft IIS FTP server with a Linux one.

**Comment by mdell-seradex** [comment]
Thanks to the completion of Castaglia#5, this is no longer required.
He has taken a different approach was works well in my tests.
